-- v122: System-Preset "US Master Scene Format (A4)"
-- Exakt kalibrierte Courier-12pt-Maße nach dem US-Monospace-Raster (10 CPI / 6 LPI),
-- adaptiert auf A4 Option A: Textspalte 60 Zeichen / 15,24 cm unverändert,
-- linker Bundsteg 3,81 cm gehalten, rechter Rand auf 1,95 cm angepasst.
--
-- Alle margin_left / margin_right in den Formaten sind relativ zur Textspalten-Kante (in cm).
-- Umrechnung: Einzug_vom_Blattrand - page_margin_left = Spaltenoffset
--   Scene Heading / Action:  3,81 - 3,81 = 0,00 cm
--   Dialogue links:          6,35 - 3,81 = 2,54 cm   |  rechts: 15,24-(2,54+8,89) = 3,81 cm
--   Parenthetical links:     7,87 - 3,81 = 4,06 cm   |  rechts: 15,24-(4,06+5,08) = 6,10 cm
--   Character:               9,40 - 3,81 = 5,59 cm

INSERT INTO absatzformat_presets (name, beschreibung, ist_system, seitenformat, page_margins, formate)
VALUES (
  'US Master Scene Format (A4)',
  'Hollywood-Standardformat exakt nach 10-CPI/6-LPI-Raster, auf A4 adaptiert (Option A: Textspalte 15,24 cm / 60 Zeichen unveraendert, Bundsteg 3,81 cm). Courier Prime 12pt.',
  true,
  'a4',
  '{"top": 2.54, "right": 1.95, "bottom": 4.30, "left": 3.81}'::jsonb,
  '[
    {
      "name": "Scene Heading",
      "kuerzel": "SH",
      "kategorie": "drehbuch",
      "font_family": "Courier Prime",
      "font_size": 12,
      "bold": true,
      "italic": false,
      "underline": false,
      "uppercase": true,
      "text_align": "left",
      "margin_left": 0,
      "margin_right": 0,
      "space_before": 24,
      "space_after": 12,
      "line_height": 1.0,
      "sort_order": 1,
      "enter_next": "Action",
      "tab_next": null
    },
    {
      "name": "Action",
      "kuerzel": "ACT",
      "kategorie": "drehbuch",
      "font_family": "Courier Prime",
      "font_size": 12,
      "bold": false,
      "italic": false,
      "underline": false,
      "uppercase": false,
      "text_align": "left",
      "margin_left": 0,
      "margin_right": 0,
      "space_before": 12,
      "space_after": 0,
      "line_height": 1.0,
      "sort_order": 2,
      "ist_standard": true,
      "enter_next": "Action",
      "tab_next": "Character"
    },
    {
      "name": "Character",
      "kuerzel": "CHAR",
      "kategorie": "drehbuch",
      "font_family": "Courier Prime",
      "font_size": 12,
      "bold": false,
      "italic": false,
      "underline": false,
      "uppercase": true,
      "text_align": "left",
      "margin_left": 5.59,
      "margin_right": 0,
      "space_before": 12,
      "space_after": 0,
      "line_height": 1.0,
      "sort_order": 3,
      "enter_next": "Dialogue",
      "tab_next": "Action"
    },
    {
      "name": "Dialogue",
      "kuerzel": "DIA",
      "kategorie": "drehbuch",
      "font_family": "Courier Prime",
      "font_size": 12,
      "bold": false,
      "italic": false,
      "underline": false,
      "uppercase": false,
      "text_align": "left",
      "margin_left": 2.54,
      "margin_right": 3.81,
      "space_before": 0,
      "space_after": 0,
      "line_height": 1.0,
      "sort_order": 4,
      "enter_next": "Character",
      "tab_next": "Parenthetical"
    },
    {
      "name": "Parenthetical",
      "kuerzel": "PAR",
      "kategorie": "drehbuch",
      "font_family": "Courier Prime",
      "font_size": 12,
      "bold": false,
      "italic": false,
      "underline": false,
      "uppercase": false,
      "text_align": "left",
      "margin_left": 4.06,
      "margin_right": 6.10,
      "space_before": 0,
      "space_after": 0,
      "line_height": 1.0,
      "sort_order": 5,
      "enter_next": "Dialogue",
      "tab_next": "Action"
    },
    {
      "name": "Transition",
      "kuerzel": "TRANS",
      "kategorie": "drehbuch",
      "font_family": "Courier Prime",
      "font_size": 12,
      "bold": false,
      "italic": false,
      "underline": false,
      "uppercase": true,
      "text_align": "right",
      "margin_left": 0,
      "margin_right": 0,
      "space_before": 12,
      "space_after": 12,
      "line_height": 1.0,
      "sort_order": 6,
      "enter_next": "Scene Heading",
      "tab_next": "Action"
    },
    {
      "name": "Shot",
      "kuerzel": "SHOT",
      "kategorie": "drehbuch",
      "font_family": "Courier Prime",
      "font_size": 12,
      "bold": false,
      "italic": false,
      "underline": false,
      "uppercase": true,
      "text_align": "left",
      "margin_left": 0,
      "margin_right": 0,
      "space_before": 12,
      "space_after": 0,
      "line_height": 1.0,
      "sort_order": 7,
      "enter_next": "Action",
      "tab_next": null
    }
  ]'::jsonb
)
ON CONFLICT (name) DO NOTHING;
