-- Migration v129: Glossar — term_en Feld + 5 neue Kategorien + 120 Excel-Datensätze

-- 1. Spalte term_en hinzufügen
ALTER TABLE dk_glossar          ADD COLUMN IF NOT EXISTS term_en TEXT NOT NULL DEFAULT '';
ALTER TABLE dk_glossar_defaults ADD COLUMN IF NOT EXISTS term_en TEXT NOT NULL DEFAULT '';

-- 2. Englische Übersetzungen für bestehende 25 Defaults (kuerzel-Kategorie)
UPDATE dk_glossar_defaults SET term_en = 'Pick-up'                            WHERE kuerzel = 'PU';
UPDATE dk_glossar_defaults SET term_en = 'Direct Pick-up'                     WHERE kuerzel = 'DPU'  AND name NOT LIKE '%(Eröffnungs%';
UPDATE dk_glossar_defaults SET term_en = 'Continuous Action'                  WHERE kuerzel = 'CA';
UPDATE dk_glossar_defaults SET term_en = 'Indirect Pick-up'                   WHERE kuerzel = 'IPU'  AND name NOT LIKE '%(Eröffnungs%';
UPDATE dk_glossar_defaults SET term_en = 'Direct Pick-up (Opening Marker)'    WHERE kuerzel = 'DPU.';
UPDATE dk_glossar_defaults SET term_en = 'Indirect Pick-up (Opening Marker)'  WHERE kuerzel = 'IPU.';
UPDATE dk_glossar_defaults SET term_en = 'Parking a storyline / Hold'         WHERE kuerzel = 'Parken';
UPDATE dk_glossar_defaults SET term_en = 'Penultimate (pre-cliffhanger scene)' WHERE kuerzel = 'PEN';
UPDATE dk_glossar_defaults SET term_en = 'Cliffhanger'                        WHERE kuerzel = 'CLIFF';
UPDATE dk_glossar_defaults SET term_en = 'Solo scene'                         WHERE kuerzel = 'SOLO';
UPDATE dk_glossar_defaults SET term_en = 'Crosscut / Intercut'                WHERE kuerzel = 'WS';
UPDATE dk_glossar_defaults SET term_en = 'Split Screen'                       WHERE kuerzel = 'Split-Screen';
UPDATE dk_glossar_defaults SET term_en = 'One-Way Phone Call'                 WHERE kuerzel = '1W';
UPDATE dk_glossar_defaults SET term_en = 'Two-Way Phone Call'                 WHERE kuerzel = '2W';
UPDATE dk_glossar_defaults SET term_en = 'Voice Over (V.O.)'                  WHERE kuerzel = 'VO';
UPDATE dk_glossar_defaults SET term_en = 'Off-screen (O.S.)'                  WHERE kuerzel = 'OFF';
UPDATE dk_glossar_defaults SET term_en = 'Sound Only'                         WHERE kuerzel = 'NT';
UPDATE dk_glossar_defaults SET term_en = 'Insert / Pre-recorded footage'      WHERE kuerzel = 'Einspieler';
UPDATE dk_glossar_defaults SET term_en = 'At production''s discretion'        WHERE kuerzel = 'NMDP' AND name NOT LIKE '%Komparsen%';
UPDATE dk_glossar_defaults SET term_en = 'At discretion (extras)'             WHERE kuerzel = 'NMDP-Komparsen';
UPDATE dk_glossar_defaults SET term_en = 'No lines (N.L.)'                    WHERE kuerzel = 'o.T.';
UPDATE dk_glossar_defaults SET term_en = 'Sexual encounter begins'             WHERE kuerzel = 'SBSA';
UPDATE dk_glossar_defaults SET term_en = 'Shadow script'                      WHERE kuerzel = 'Schattenbuch';
UPDATE dk_glossar_defaults SET term_en = 'Casting scene'                      WHERE kuerzel = 'Casting-Szene';
UPDATE dk_glossar_defaults SET term_en = 'Spin-off'                           WHERE kuerzel = 'Spin-Off';

-- 3. Bestehende dk_glossar-Einträge (Produktions-Kopien) per Kürzel+Name rückwärts befüllen
UPDATE dk_glossar g
SET term_en = d.term_en
FROM dk_glossar_defaults d
WHERE g.kuerzel = d.kuerzel AND g.name = d.name AND g.term_en = '' AND d.term_en <> '';

-- 4. Neue Defaults aus Excel (120 Einträge — 5 neue Kategorien)
INSERT INTO dk_glossar_defaults (kuerzel, name, erklaerung, term_en, kategorie, sort_order) VALUES
  ('', 'A-Plot', 'Haupthandlung einer Episode/Staffel; trägt den dramatischen Hauptkonflikt und die grösste Bildschirmzeit. In Soaps häufig die zentrale Liebes- oder Familiengeschichte einer Staffel.', 'A-Story / A-Plot', 'dramaturgie', 100),
  ('', 'Akt', 'Grosser Erzählabschnitt mit dramaturgischer Eigenfunktion. In der Drei-Akt-Struktur (Aristoteles -> Syd Field): Exposition / Konfrontation / Auflösung. In der Fünf-Akt-Struktur (Freytag, klassisches Drama): Exposition, steigende Handlung, Höhepunkt/Peripetie, fallende Handlung, Katastrophe/Lösung. Akte werden in serieller TV-Produktion oft auch innerhalb einer Episode genutzt (US-Network-Schema: Teaser + 4-5 Akte um Werbeunterbrechungen herum).', 'Act', 'dramaturgie', 101),
  ('', 'Antagonist', 'Figur (oder Kraft), die den Protagonisten am Erreichen seines Ziels hindert. Muss kein ''Schurke'' sein, sondern jede systematische Gegenkraft (z. B. ein konkurrierender Charakter, eine Institution, ein innerer Konflikt).', 'Antagonist', 'dramaturgie', 102),
  ('', 'Anthologie-Serie', 'Serie, deren Episoden oder Staffeln in sich abgeschlossene Geschichten mit (meist) wechselndem Personal erzählen (z. B. Black Mirror, Fargo). Steht im Gegensatz zur fortlaufenden, hochserialisierten Soap.', 'Anthology series', 'dramaturgie', 103),
  ('', 'Auflösung (dramaturgisch)', 'Letzte Phase einer Geschichte nach dem Höhepunkt: lose Fäden werden zusammengeführt, der neue Zustand der Welt etabliert. Vorsicht: ''Auflösung'' hat in der Regie eine zweite Bedeutung (siehe Abschnitt E).', 'Resolution / Denouement', 'dramaturgie', 104),
  ('', 'Auslösendes Ereignis', 'Das Ereignis, das den Protagonisten aus dem Status quo reisst und die Hauptgeschichte in Gang setzt. Bei McKee zentrales Element (''inciting incident''), in der ersten Akt-Hälfte.', 'Inciting Incident / Catalyst', 'dramaturgie', 105),
  ('', 'B-Plot', 'Nebenhandlung einer Episode; trägt häufig das thematische Echo der A-Story oder dient als emotionale Kontrastfolie (klassisch in Save-the-Cat: Liebesgeschichte als B-Story).', 'B-Story / B-Plot', 'dramaturgie', 106),
  ('', 'Backstory', 'Vorgeschichte einer Figur vor Beginn der erzählten Handlung. Wird dosiert über Exposition, Dialog oder Rückblenden eingeführt.', 'Backstory', 'dramaturgie', 107),
  ('', 'Beat', 'Kleinste dramaturgische Bewegungseinheit: ein Moment, an dem sich Wert, Handlung oder emotionaler Zustand ändert (vgl. McKee: ''a beat is an exchange of behavior in action/reaction''). Eine Szene besteht aus mehreren Beats.', 'Beat', 'dramaturgie', 108),
  ('', 'Beat Sheet', 'Strukturierte Liste aller wichtigen Story-Beats (Wendepunkte) eines Projekts mit Funktion, Inhalt und ungefährer Position. Beat Sheets sind Arbeitsgrundlage in Writers-Rooms; bekannteste Vorlagen: Save the Cat (15 Beats), Heldenreise (12 Stufen), Story Circle (8 Schritte).', 'Beat sheet', 'dramaturgie', 109),
  ('', 'C-Plot', 'Dritter, oft komödiantischer oder weniger dramatischer Handlungsstrang in einer Episode; bei Ensemble-Serien und Soaps verbreitet.', 'C-Story / C-Plot', 'dramaturgie', 110),
  ('', 'Charakterbogen', 'Innere Entwicklung einer Figur über die Geschichte: vom Anfangszustand über Krisen zum veränderten Endzustand. Positiv (Lernen/Wachsen), negativ (Korrumpierung) oder ''flat arc'' (Figur ändert die Welt, nicht sich selbst).', 'Character Arc', 'dramaturgie', 111),
  ('', 'Cliffhanger', 'Offenes, hochspannungsgeladenes Ende einer Szene, Episode oder Staffel, das die Frage ''Wie geht es weiter?'' unbeantwortet lässt. In deutschen Dailys typischerweise vor jeder Werbe-Insel und am Folgenende.', 'Cliffhanger', 'dramaturgie', 112),
  ('', 'Climax / Höhepunkt', 'Dramaturgisch entscheidende Konfrontation; Moment der höchsten Spannung, in dem die zentrale dramatische Frage beantwortet wird (McKee: ''obligatory scene'').', 'Climax', 'dramaturgie', 113),
  ('', 'Cold Open', 'Erste Szene einer Episode, die vor dem Vorspann gespielt wird und das Publikum sofort emotional/inhaltlich hineinzieht. Oft synonym zu Teaser verwendet, technisch aber spezifisch der Pre-Title-Block.', 'Cold Open', 'dramaturgie', 114),
  ('', 'Crisis (McKee)', 'Bei Robert McKee die Decision zwischen unvereinbaren Werten kurz vor dem Climax - der ''Do or die''-Moment, in dem die Figur den finalen Wertwandel vollziehen muss. Crisis -> Climax -> Resolution sind die letzten drei der fünf Elemente seines Story-Modells.', 'Crisis', 'dramaturgie', 115),
  ('', 'Drei-Akt-Struktur', 'Vorherrschendes Strukturmodell des US-Mainstreamkinos: Setup (ca. 25 %) - Konfrontation (ca. 50 %) - Auflösung (ca. 25 %). Akt-Übergänge sind Plot Points. Popularisiert durch Syd Field (Screenplay, 1979).', 'Three-act structure', 'dramaturgie', 116),
  ('', 'Ensemble', 'Konstellation von vier oder mehr gleichberechtigten Hauptfiguren ohne klassisch dominanten Einzel-Protagonisten. Charakteristisch für Soaps, Daily-Serien und Ensemble-Dramen.', 'Ensemble cast', 'dramaturgie', 117),
  ('', 'Expose', 'Deutscher Sprachgebrauch: ausführliche Stoffvorstellung von ca. 5-10 Seiten, in Fliesstext, ohne Dialog, mit klarer Drei-Akt-Gliederung; Zwischenstufe zwischen Logline und Treatment. Achtung: im englischsprachigen Raum kein etabliertes Pendant - engl. synopsis oder outline deckt das oft mit ab.', 'Treatment (short) / Synopsis', 'dramaturgie', 118),
  ('', 'Exposition', 'Vermittlung der für das Verständnis nötigen Informationen (Welt, Figuren, Vorgeschichte, Beziehungen). Hohe Kunst: Exposition unsichtbar in Konflikt und Handlung verpacken (''show, don''t tell'').', 'Exposition', 'dramaturgie', 119),
  ('', 'Fatal Flaw', 'Tragischer Charakterfehler, der die Figur in die Katastrophe führt (Hybris bei Aristoteles). Im positiven Bogen oft die Schwäche, die der Protagonist überwinden muss, um sein Need zu erreichen.', 'Fatal Flaw / Tragic Flaw', 'dramaturgie', 120),
  ('', 'Field-Paradigma', 'Syd Fields Drei-Akt-Modell mit definierten Strukturpunkten: Inciting Incident (~S. 10), Plot Point 1 (Ende Akt I, ~S. 25-27), Pinch 1, Midpoint (~S. 60), Pinch 2, Plot Point 2 (Ende Akt II, ~S. 85-90), Climax, Resolution. Seitenzahlen beziehen sich auf ein 120-seitiges Drehbuch.', 'Field''s Paradigm', 'dramaturgie', 121),
  ('', 'Foil', 'Kontrastfigur, die durch Gegensatz Eigenschaften des Protagonisten herausarbeitet (z. B. Watson zu Holmes, Draco zu Harry).', 'Foil', 'dramaturgie', 122),
  ('', 'Fünf-Akt-Struktur', 'Gustav Freytags klassisches Pyramidenmodell: Exposition, erregendes Moment, Höhepunkt mit Peripetie, retardierendes Moment, Katastrophe/Lösung. Wurzel im antiken/elisabethanischen Drama.', 'Five-Act Structure', 'dramaturgie', 123),
  ('', 'Heldenreise', 'Universelles Erzählmuster nach Joseph Campbell (Der Heros in tausend Gestalten, 1949), für das Drehbuch in 12 Stufen popularisiert durch Christopher Vogler (The Writer''s Journey, 1992): Gewohnte Welt, Ruf des Abenteuers, Verweigerung, Begegnung mit dem Mentor, Schwellenübertritt, Bewährungsproben/Verbündete/Feinde, Vordringen zur tiefsten Höhle, Entscheidungskampf, Belohnung, Rückweg, Auferstehung, Rückkehr mit dem Elixier.', 'Hero''s Journey / The Writer''s Journey', 'dramaturgie', 124),
  ('', 'Höhepunkt', 'Siehe Climax.', 'Climax', 'dramaturgie', 125),
  ('', 'Logline', 'Ein- bis Zweisatz-Zusammenfassung der Story, die Protagonist, Konflikt, Einsatz und Genre bündelt; Verkaufs- und Klärungswerkzeug.', 'Logline', 'dramaturgie', 126),
  ('', 'McKee-Modell', 'Story-Theorie nach Robert McKee (Story, 1997). Fünf zentrale Elemente jeder Geschichte: Inciting Incident, Progressive Complications, Crisis, Climax, Resolution. Betont Wertewandel in jeder Szene, ''Controlling Idea'' und Subtext.', 'McKee / Story Principles', 'dramaturgie', 127),
  ('', 'Midpoint', 'Wendepunkt etwa in der Mitte des zweiten Akts, der die Richtung der Geschichte fundamental verändert (häufig: Sieg in eine Niederlage oder umgekehrt, oder Wechsel von want zu need).', 'Midpoint', 'dramaturgie', 128),
  ('', 'Nebenhandlung', 'Sekundärer Handlungsstrang neben der Haupthandlung; spiegelt thematisch das Hauptthema oder dient der Charakterentwicklung.', 'Subplot', 'dramaturgie', 129),
  ('', 'Need', 'Tiefes, oft unbewusstes Bedürfnis der Figur (das, was sie wirklich braucht, um ganz zu werden); steht häufig im Widerspruch zum Want. Auflösung des Need-Konflikts = innerer Bogen.', 'Need', 'dramaturgie', 130),
  ('', 'Outline', 'Strukturierter Handlungsabriss; in der seriellen Produktion ein Zwischenstand zwischen Storyline und Dialogbuch (siehe Abschnitt D).', 'Outline', 'dramaturgie', 131),
  ('', 'Payoff', 'Auflösung eines zuvor gepflanzten Setups (''Tschechows Gewehr''); macht eine Vorbereitung im dritten Akt wirksam.', 'Payoff', 'dramaturgie', 132),
  ('', 'Pinch', '''Klemmpunkt'' bei Syd Field: zwei Erinnerungs-Szenen (Pinch 1 ca. 3/8, Pinch 2 ca. 5/8 des Drehbuchs), die den zentralen Konflikt re-aktivieren und die Macht des Antagonisten zeigen.', 'Pinch / Pinch point', 'dramaturgie', 133),
  ('', 'Plot Point', 'Grosser Wendepunkt, der die Handlung in eine neue Richtung kippt. Field unterscheidet PP1 (Übergang Akt I -> II) und PP2 (Übergang II -> III).', 'Plot Point / Turning Point', 'dramaturgie', 134),
  ('', 'Procedural', 'Genrekategorie, in der jede Episode einen abgeschlossenen Fall/Problem löst (Krimi, Medical, Legal); langlaufende Figurenbögen liegen darunter.', 'Procedural', 'dramaturgie', 135),
  ('', 'Progressive Complications', 'Bei McKee die zweite Stufe nach dem Inciting Incident: Eskalation von Konflikten, die den Protagonisten an immer grössere ''points of no return'' zwingt.', 'Progressive complications', 'dramaturgie', 136),
  ('', 'Protagonist', 'Hauptfigur, deren bewusstes Ziel und Wertewandel die Erzählung trägt. Bei Ensembles können mehrere Protagonist:innen parallel existieren.', 'Protagonist', 'dramaturgie', 137),
  ('', 'Save the Cat Beats', 'Beat Sheet von Blake Snyder (Save the Cat!, 2005), 15 Beats: Opening Image, Theme Stated, Set-Up, Catalyst, Debate, Break into Two, B Story, Fun and Games, Midpoint, Bad Guys Close In, All Is Lost, Dark Night of the Soul, Break into Three, Finale (5 Steps), Final Image. Jeder Beat hat eine ungefähre Seitenposition.', 'Save the Cat Beat Sheet', 'dramaturgie', 138),
  ('', 'Sequenz', 'Mehrere thematisch zusammengehörige Szenen, die einen gemeinsamen Mini-Bogen bilden (z. B. ''Trainingssequenz'', ''Verfolgungssequenz''). Vergleichbar dem Kapitel im Roman.', 'Sequence', 'dramaturgie', 139),
  ('', 'Sequenz-Methode (8-Sequenzen-Modell)', 'Methode nach Frank Daniel (USC): Drei-Akt-Struktur wird in 8 Sequenzen unterteilt (2 in Akt I, 4 in Akt II, 2 in Akt III), jede mit eigenem Mini-Spannungsbogen und Sequenz-Climax.', 'Eight-Sequence Method', 'dramaturgie', 140),
  ('', 'Setup', 'Erste Phase der Geschichte (Akt I): Vorstellung der Welt, der Figuren und des Status quo, bis das auslösende Ereignis greift. Auch: das Pflanzen eines Elements, das später im Payoff aufgelöst wird.', 'Setup', 'dramaturgie', 141),
  ('', 'Step Outline', 'Handlungsabriss in einzelnen, durchnummerierten Handlungs-/Story-Schritten (Steps); jede Etappe ist ein Beat oder Mini-Szene. Wird in Writers-Rooms vor dem Treatment verwendet.', 'Step Outline', 'dramaturgie', 142),
  ('', 'Story Circle (Dan Harmon)', 'Acht-Schritte-Modell, abgeleitet aus Campbells Heldenreise, entwickelt von TV-Autor Dan Harmon (Community, Rick and Morty): 1) You - 2) Need - 3) Go - 4) Search - 5) Find - 6) Take - 7) Return - 8) Change. Besonders geeignet für Episoden mit klarer Figuren-Transformation.', 'Story Circle / Plot Embryo', 'dramaturgie', 143),
  ('', 'Subplot', 'Siehe Nebenhandlung.', 'Subplot', 'dramaturgie', 144),
  ('', 'Synopsis', 'Kurzzusammenfassung der Story in Fliesstext, je nach Kontext 1/2 bis 2 Seiten. Im US-Kontext oft synonym zum deutschen Expose.', 'Synopsis', 'dramaturgie', 145),
  ('', 'Szene', 'Erzähleinheit, die einen räumlichen und zeitlichen Zusammenhang umfasst. Eine neue Szene beginnt mit Schauplatz- oder Zeitwechsel. Sollte mindestens einen Wertewandel (Beat) enthalten.', 'Scene', 'dramaturgie', 146),
  ('', 'Szenenbild', 'Im deutschen Sprachgebrauch mehrdeutig: 1) Szenenkopf/Slugline als Überschrift einer Szene; 2) szenografisches Bild/Set-Design. Vorsicht bei Kommunikation mit Gewerken.', 'Slugline / Set design', 'dramaturgie', 147),
  ('', 'Tag (Schlussszene)', 'Kurze Schlussszene nach dem Climax, oft als emotionale oder humoristische Coda; in US-Sitcoms üblich. Nicht zu verwechseln mit ''Tag/Nacht'' als Tageszeit-Angabe in der Slugline.', 'Tag', 'dramaturgie', 148),
  ('', 'Teaser', 'Sehr kurzer, hochverdichteter Anfang einer Episode (vor Vorspann), der Aufmerksamkeit erzeugt und ein narratives Versprechen platziert. In Krimis: oft die Tat oder die Leiche.', 'Teaser', 'dramaturgie', 149),
  ('', 'Treatment', 'Deutscher Sprachgebrauch: ausführliche, szenisch-prosaisch geschriebene Stoffbeschreibung (20-60+ Seiten), Endstufe vor dem Drehbuch. US-Sprachgebrauch: treatment kann auch deutlich kürzer sein (5-15 Seiten). Die Begriffe sind nicht 1:1 deckungsgleich.', 'Treatment', 'dramaturgie', 150),
  ('', 'Want', 'Bewusstes äusseres Ziel der Figur - das, was sie zu wollen glaubt. Steht häufig in Spannung zum Need.', 'Want', 'dramaturgie', 151),
  ('', 'Wendepunkt', 'Allgemeine Bezeichnung für eine Szene, die die Handlung in eine substantiell neue Richtung kippt. Plot Points sind Wendepunkte erster Ordnung.', 'Turning Point', 'dramaturgie', 152),
  ('', 'Emotionaler Bogen', 'Verlauf der affektiven Valenz einer Geschichte (positiv/negativ) über ihre Erzählzeit. Quantifizierbar durch Sentiment-Scoring auf gleitenden Fenstern und Visualisierung als Zeitreihe.', 'Emotional arc', 'emotional_bogen', 200),
  ('', 'Block / Drehblock', 'Produktionseinheit, in der eine definierte Anzahl Folgen (oft 20-30 Episoden) gemeinsam organisiert, geplant und gedreht werden. Grundlogik der industriellen Daily-Produktion.', 'Production block / Shooting block', 'serien_struktur', 300),
  ('', 'Blockabnahme', 'Formaler Freigabe-Schritt durch die Redaktion / Producer für einen ganzen Drehblock - bündelt mehrere Buch-/Outline-Abnahmen.', 'Block approval', 'serien_struktur', 301),
  ('', 'Buchabnahme', 'Formale Freigabe eines Drehbuchs (Dialogbuch) durch die Redaktion bzw. Headautor:innen; Voraussetzung für die Disposition durch die Produktion.', 'Script approval / Greenlight', 'serien_struktur', 302),
  ('', 'Daily Soap', 'Werktäglich (Mo-Fr) ausgestrahltes Endlos-Serienformat ohne festgelegtes Ende, mit Ensemble, mehreren parallelen Strängen und stark verlangsamtem Erzähltempo, damit nicht gesehene Folgen schnell aufgeholt werden können.', 'Daily soap opera', 'serien_struktur', 303),
  ('', 'Dialogbuch', 'Letzte Stufe vor dem Dreh: vollständig ausgeschriebenes Drehbuch mit allen Dialogen, Szenenanweisungen und Sluglines. In der deutschen Soap-Produktion oft synonym mit ''Drehbuch der Folge''.', 'Shooting script / Final dialogue draft', 'serien_struktur', 304),
  ('', 'Disposition (Tagesdispo)', 'Tagesplan für einen konkreten Drehtag: welche Szenen, welche Darsteller:innen, welche Locations, Drehbeginn/-ende, Fahr- und Maskenzeiten.', 'Call sheet / Daily call sheet', 'serien_struktur', 305),
  ('', 'Drehplan', 'Übergeordneter Zeit- und Ablaufplan über mehrere Drehtage; ordnet Szenen nach Location, Verfügbarkeit, Tag/Nacht und Kostenlogik. In Deutschland erstellt von Produktionsleitung / 1. Aufnahmeleitung. In der US vom 1.AD', 'Shooting schedule', 'serien_struktur', 306),
  ('', 'Episode / Folge', 'Eine einzelne Ausstrahlungs-/Sendeeinheit.', 'Episode', 'serien_struktur', 307),
  ('', 'Folgenkonzept', 'Konzept einer einzelnen Folge: ihre Strang-Mischung, ihr A/B/C-Plot-Layout, ihr Spannungsbogen und Cliffhanger. Wird in der Konzeptphase zwischen Storyline und Outline verfeinert.', 'Episode concept', 'serien_struktur', 308),
  ('', 'Headautor:in', 'Leitende:r Autor:in eines Writers-Rooms, verantwortlich für narrative Gesamtlinie, Konsistenz und kreative Letztentscheidung.', 'Showrunner / Head writer', 'serien_struktur', 309),
  ('', 'Outline', 'Detaillierte, beat-weise Skizze einer Folge mit allen Szenen, Strang-Wechseln und Handlungslogik; Zwischenstufe zwischen Storyline und Dialogbuch.', 'Outline / Beat sheet', 'serien_struktur', 310),
  ('', 'Plotten', 'Iteratives Erarbeiten eines Folgen-/Block-Plots im Team (Plot-Konferenz / Plotting Room).', 'Plotting / Breaking story', 'serien_struktur', 311),
  ('', 'Staffel', 'Eine Sende-Saison.', 'Season', 'serien_struktur', 312),
  ('', 'Storyline / Strang', 'Längerfristiger Handlungsstrang einer Figur oder Figurengruppe (z. B. ''Anna-Strang'', ''Johanna-Strang''), der über viele Folgen läuft und in jeder Folge in dosierten Beats vorangetrieben wird.', 'Storyline / Story arc', 'serien_struktur', 313),
  ('', 'Storyliner:in', 'Autor:in, die Storylines (Szenenabrisse) entwickelt - eine Spezialrolle in der industriellen TV-Produktion (Daily/Telenovela), oft fest angestellt.', 'Storyliner', 'serien_struktur', 314),
  ('', 'Telenovela', 'Serielles Format mit klar abgeschlossener Geschichte (typischerweise eine durchgehende Liebesgeschichte über mehrere hundert Folgen) und definiertem Ende. Wichtigster Unterschied zur Daily Soap: feste Story-Architektur mit Anfang, Mittelteil, Ende.', 'Telenovela', 'serien_struktur', 315),
  ('', 'Weekly', 'Wöchentlich ausgestrahlte fiktionale Serie (z. B. Tatort); im Unterschied zur Daily Soap höhere Produktionsdichte und stärker geschlossene Episodenform.', 'Weekly series', 'serien_struktur', 316),
  ('', 'Writers'' Room', 'Räumlicher und organisatorischer Rahmen, in dem ein Autor:innen-Team kollektiv die Stoffentwicklung betreibt.', 'Writers'' room', 'serien_struktur', 317),
  ('', 'Action / Szenenanweisung', 'Beschreibender Text in einer Szene: was geschieht, was zu sehen ist; im Präsens, knapp, visuell. Keine inneren Gedanken, keine Kamera-Sprache (ausser wenn unvermeidbar).', 'Action / Description', 'format_produktion', 400),
  ('', 'Auflösung (Regie)', 'Zerlegung einer Szene in einzelne Einstellungen durch die Regie: welcher Bildausschnitt, welche Achse, welcher Schnitt. Nicht zu verwechseln mit dramaturgischer ''Auflösung'' (Resolution).', 'Shot breakdown / Decoupage', 'format_produktion', 401),
  ('', 'Courier 12pt', 'Im US-Master-Scene-Format vorgeschriebene Monospace-Schrift. Historisch von Schreibmaschinen; nicht-proportional, daher 10 Anschläge = 1 Zoll horizontal, 6 Zeilen = 1 Zoll vertikal. Ermöglicht die ''1 Seite = 1 Filmminute''-Daumenregel.', 'Courier 12pt', 'format_produktion', 402),
  ('', 'Dialog', 'Gesprochener Text einer Figur; im US-Format zentriert unter dem Figurennamen.', 'Dialogue', 'format_produktion', 403),
  ('', 'Drehbuch-Standardformat (US)', '''Master Scene Format'': Courier 12pt, monospaced, definierte Seitenränder, Slugline links oben, Dialog zentriert. Daumenregel: 1 Seite = 1 Filmminute. International dominant, auch in Deutschland weitgehend übernommen.', 'US screenplay format / Master Scene Format', 'format_produktion', 404),
  ('', 'Drehbuchformat (deutsch)', 'Historisch: zweispaltiges Format (Bild/Ton getrennt) oder ''Theaterstück-Format''. Heute grösstenteils dem US-Format angenähert (A4 statt Letter, ansonsten gleiche Logik).', 'German screenplay format', 'format_produktion', 405),
  ('', 'Einstellung', 'Kleinste filmische Bildeinheit, vom Anlaufen bis zum Auslaufen der Kamera; mehrere Einstellungen -> Szene. Im Drehbuch-Spec script üblicherweise nicht explizit ausnotiert.', 'Shot', 'format_produktion', 406),
  ('EXT.', 'EXT.', 'Slugline-Marker für Aussenaufnahme (''Exterior'').', 'EXT. (Exterior)', 'format_produktion', 407),
  ('FDX', 'Final Draft / FDX', 'Marktführende kommerzielle Drehbuch-Software (Final Draft Inc.). FDX = XML-basiertes Dateiformat. Branchenstandard für Austausch von Drehbüchern mit Produktion, Sender, Verlag.', 'Final Draft / FDX', 'format_produktion', 408),
  ('', 'Fountain', 'Offenes, plaintext-basiertes Markup-Format für Drehbücher (Spec von John August, Stu Maschwitz et al., basierend auf Markdown). Ermöglicht das Schreiben in beliebigen Texteditoren; Konvertierung in formatierte PDF/FDX über Tools wie Highland, Slugline etc. Vorteil: zukunftssicher und werkzeugunabhängig.', 'Fountain (markup)', 'format_produktion', 409),
  ('INT.', 'INT.', 'Slugline-Marker für Innenaufnahme (''Interior'').', 'INT. (Interior)', 'format_produktion', 410),
  ('INT./EXT.', 'INT./EXT.', 'Kombinierter Marker für Szenen, die innen und aussen spielen (z. B. Auto-Innenraum mit Fahrt durch Stadt).', 'INT./EXT.', 'format_produktion', 411),
  ('', 'Master Scene Heading', 'Primäre Szenenüberschrift, die Ort, Innen/Aussen und Tageszeit definiert. Synonym zu ''Primary Slugline''.', 'Master Scene Heading', 'format_produktion', 412),
  ('', 'NACHT', 'Tageszeit-Angabe in der Slugline (Standard: DAY/NIGHT).', 'NIGHT', 'format_produktion', 413),
  ('', 'Parenthetical / Regieanweisung', 'Kurze Anmerkung in Klammern unter dem Figurennamen, vor dem Dialog - beschreibt Sprechweise oder kleine Aktion (''(leise)'', ''(wütend)''). Sparsam einsetzen.', 'Parenthetical / Wryly', 'format_produktion', 414),
  ('', 'Secondary Heading', 'Unterüberschrift innerhalb einer Master-Szene, die einen Schauplatzwechsel im selben räumlichen Zusammenhang markiert (z. B. Master: ''INT. HAUS - TAG''; Secondary: ''WOHNZIMMER'', ''KUECHE'').', 'Secondary heading / Subheading', 'format_produktion', 415),
  ('', 'Seitenraster / Master Scene Format-Masse', 'Festes Zeichenraster statt typografisches Layout. Courier 12pt = 10 Anschläge/Zoll (1 Zeichen = 2,54 mm breit) und 6 Zeilen/Zoll (1 Zeile = 4,23 mm hoch). 1 Zoll = 2,54 cm. Standardränder auf Letter: links 1,5 Zoll (3,81 cm, Bindung), rechts/oben/unten je 1,0 Zoll (2,54 cm). Textspalte: 6,0 Zoll = 15,24 cm = 60 Zeichen; 9,0 Zoll = 22,86 cm = 54 Zeilen. Bei Übertragung auf A4 Raster beibehalten, nur Ränder anpassen: linker Bindungsrand 3,81 cm bleibt, rechter Rand schrumpft auf ca. 1,95 cm, vertikal lieber den unteren Rand vergrössern als Zeilen hinzufügen - sonst driftet die ''1 Seite = 1 Minute''-Regel.', 'Page grid / Screenplay margins', 'format_produktion', 416),
  ('', 'Shooting Script', 'Drehbuchfassung mit fortlaufender Szenen- und Einstellungs-Nummerierung, Versions-Farbcodes (US-Praxis) und allen Produktionsmarkern.', 'Shooting Script', 'format_produktion', 417),
  ('', 'Shot', 'Siehe Einstellung. Im Spec script nur selten ausnotiert; eher im Shooting Script.', 'Shot', 'format_produktion', 418),
  ('', 'Slugline / Szenenüberschrift', 'Erste Zeile jeder Szene, in Grossbuchstaben: INT./EXT. - ORT - TAG/NACHT. Definiert räumlich-zeitliche Verortung und steuert Kalkulation/Drehplanung.', 'Slugline / Scene heading', 'format_produktion', 419),
  ('', 'TAG', 'Tageszeit-Angabe in der Slugline (siehe NACHT). Cave: nicht mit dem dramaturgischen ''Tag'' (Schlussszene) verwechseln.', 'DAY', 'format_produktion', 420),
  ('', 'Transition / Überblendung', 'Übergangsanweisung zwischen Szenen (CUT TO:, FADE OUT., DISSOLVE TO:). In modernen Spec scripts sparsam eingesetzt.', 'Transition', 'format_produktion', 421),
  ('', 'US Letter', 'Standard-Papierformat des US-Drehbuchs: 8,5 x 11 Zoll = 21,59 x 27,94 cm. Erster Stolperstein bei Übertragung nach Deutschland, da A4 (21,0 x 29,7 cm) abweicht: ca. 6 mm schmaler, ca. 18 mm höher.', 'US Letter', 'format_produktion', 422),
  ('', 'Yamdu', 'Cloud-basierte Filmproduktions-Management-Software (Buchimport aus Final Draft/PDF, Szenen-Breakdown, Drehplan/Stripboard, Cast/Crew-Listen, Call Sheets, Gantt-Übersicht). Wird u. a. von National Geographic, NBCUniversal, Constantin Film, ServusTV sowie deutschen Produktionen (z. B. Joyn/Pantaflix ''Das Internat'') eingesetzt; bietet eine MovieLabs-OMC-basierte API.', 'Yamdu', 'format_produktion', 423),
  ('API', 'API', '''Application Programming Interface'' - definierte Schnittstelle, über die andere Programme/Dienste mit der App kommunizieren (typischerweise REST/JSON oder GraphQL).', 'API', 'app_architektur', 500),
  ('', 'Background Sync', 'Web-Plattform-API, die es einer PWA erlaubt, ausstehende Aktionen (z. B. Szenen-Speicherungen) zu queuen und automatisch zu synchronisieren, sobald wieder Netz vorhanden ist.', 'Background Sync API', 'app_architektur', 501),
  ('', 'Block (Datenmodell)', 'Datenobjekt im App-Datenmodell: eine geordnete Sammlung von Episoden, die als Produktionseinheit verwaltet werden. Parent von Episode.', 'Block', 'app_architektur', 502),
  ('', 'Cache API', 'Browser-API, mit der Service Worker HTTP-Antworten als Key-Value-Paare (Request -> Response) ablegen. Komplementär zu IndexedDB: Cache API speichert Netzwerkantworten (Assets, HTML), IndexedDB Anwendungsdaten (Szenen, Beats).', 'Cache API', 'app_architektur', 503),
  ('DSGVO', 'DSGVO', 'Datenschutz-Grundverordnung (EU 2016/679). Relevant für script.serienwerft.app, weil Texteingaben (Drehbücher, Plots) personenbezogene und urheberrechtlich geschützte Inhalte enthalten können. Bei KI-Textanalyse besonders kritisch: Rechtsgrundlage, Zweckbindung, Auftragsverarbeitung, ggf. Datenminimierung.', 'GDPR', 'app_architektur', 504),
  ('', 'Entity / Entität', 'Generisches Datenobjekt im App-Datenmodell: alles, was eine eigene Identität und einen Lebenszyklus hat (Figur, Location, Requisite, Strang, ...). Wird über EntityLinks mit Szenen verknüpft.', 'Entity', 'app_architektur', 505),
  ('', 'EntityLink', 'Verbindungsobjekt, das eine Entität (z. B. Figur) mit einem Kontext (z. B. einer Szene oder einem LineItem) verbindet - typischerweise mit Rolle und Metadaten (z. B. ''Sprecher'', ''Erwähnt'').', 'Entity link', 'app_architektur', 506),
  ('', 'Episode (Datenmodell)', 'Datenobjekt: eine Folge, Kind eines Blocks, enthält Stages und Szenen.', 'Episode', 'app_architektur', 507),
  ('', 'IndexedDB', 'Im Browser eingebaute, transaktionale Schlüssel-Wert-/Object-Store-Datenbank für strukturierte Daten; ermöglicht Offline-Speicherung grosser Datenmengen (z. B. ganze Drehbücher) und ist Standard-Backend für Offline-First-PWAs.', 'IndexedDB', 'app_architektur', 508),
  ('JSON', 'JSON', '''JavaScript Object Notation'' - sprach-/plattformunabhängiges Textformat für strukturierte Daten. Standard-Austauschformat in Web-APIs und auch internes Speicherformat von TipTap-Dokumenten (Baum aus Nodes und Marks).', 'JSON', 'app_architektur', 509),
  ('', 'LineItem', 'Datenobjekt der App: eine einzelne strukturierte Zeile in einer Szene (z. B. Dialog-Zeile, Action-Block, Slugline) - die kleinste adressierbare Texteinheit. Erlaubt feingranulare Verknüpfung mit Entitäten und Sentiment-Werten.', 'Line item', 'app_architektur', 510),
  ('', 'Manifest (Web App Manifest)', 'JSON-Datei einer PWA mit Metadaten (Name, Icon, Start-URL, Display-Modus), die es Browsern erlaubt, die App auf dem Home-Screen zu installieren.', 'Web App Manifest', 'app_architektur', 511),
  ('', 'Offline-First', 'Architekturprinzip: die App ist primär offline-fähig konzipiert. Daten werden zuerst lokal gespeichert (IndexedDB), die Synchronisation mit dem Server ist eine Optimierung. Erhöht Robustheit gegen Netzausfälle und Wartezeiten.', 'Offline-first', 'app_architektur', 512),
  ('', 'Project (Datenmodell)', 'Wurzelobjekt im Datenmodell: ein Projekt (z. B. eine ganze Serie wie Rote Rosen). Enthält Blocks -> Episodes -> Stages -> Scenes.', 'Project', 'app_architektur', 513),
  ('', 'ProseMirror', 'Open-Source-Bibliothek (Marijn Haverbeke) zum Bau von WYSIWYG-Rich-Text-Editoren im Browser; arbeitet mit strikter Document-Schema-Definition und transaktionalen State-Updates. Bildet das technische Fundament von TipTap und kommt u. a. bei New York Times, The Guardian und Atlassian zum Einsatz.', 'ProseMirror', 'app_architektur', 514),
  ('PWA', 'PWA', '''Progressive Web App'' - eine über den Browser ausgelieferte App mit Manifest, Service Worker und nativ-ähnlichem Verhalten (Installation, Offline-Betrieb, Push-Benachrichtigungen).', 'Progressive Web App', 'app_architektur', 515),
  ('', 'Scene (Datenmodell)', 'Datenobjekt für eine einzelne Szene, Kind einer Stage. Enthält Slugline-Metadaten, eine Liste von LineItems sowie EntityLinks.', 'Scene', 'app_architektur', 516),
  ('', 'Scene-Locking / Szenen-Sperrung', 'Mechanismus, der parallele Bearbeitungen verhindert: wenn ein:e Nutzer:in eine Szene öffnet, wird sie für andere read-only (oder mit Konflikt-Warnung). Verhindert Verlust von Änderungen im kollaborativen Schreiben - alternativ zu OT/CRDT-Live-Kollaboration.', 'Scene locking', 'app_architektur', 517),
  ('', 'Service Worker', 'JavaScript-Skript, das im Hintergrund läuft (in einem eigenen Thread) und Netzwerk-Requests einer Web-App abfangen kann; Grundlage für Offline-Caching, Background Sync und Web Push in PWAs.', 'Service Worker', 'app_architektur', 518),
  ('SSO', 'SSO', '''Single Sign-On'' - Nutzer:in meldet sich einmal an einem Identity Provider (z. B. Studio-Hamburg-Konto, Google Workspace) an und kann mehrere Anwendungen ohne erneutes Login nutzen (OAuth 2.0 / OIDC / SAML).', 'Single Sign-On', 'app_architektur', 519),
  ('', 'Stage (Datenmodell)', 'Datenobjekt: ein Bearbeitungs-/Workflow-Status oder eine Sektion innerhalb einer Episode (z. B. Storyline -> Outline -> Dialogbuch). Kind einer Episode, Parent von Scenes. Achtung Doppeldeutigkeit: nicht zu verwechseln mit ''Stage'' als Studio-Bühne (Produktion).', 'Stage', 'app_architektur', 520),
  ('', 'TipTap', 'Headless-Rich-Text-Editor-Framework auf Basis von ProseMirror, framework-agnostisch (React, Vue, Vanilla JS) mit erweiterbarem Extension-System. Speichert Dokumente als JSON-Baum aus Nodes und Marks. MIT-Lizenz; eingesetzt für den Drehbuch-Editor von script.serienwerft.app.', 'TipTap', 'app_architektur', 521),
  ('', 'Web Push', 'Web-Standard, mit dem eine PWA Push-Benachrichtigungen empfangen kann, auch wenn der Tab geschlossen ist (Service Worker + Push Service des Browsers). Auf iOS seit 16.4 nur für installierte PWAs.', 'Web Push', 'app_architektur', 522),
  ('', 'Webhook', 'HTTP-Callback: externer Dienst sendet bei einem Ereignis automatisch eine HTTP-POST-Anfrage an eine konfigurierte URL der App (z. B. ''neue Folge in Yamdu freigegeben''). Grundlage für Event-getriebene Integrationen.', 'Webhook', 'app_architektur', 523);
